// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
window.FIREHUB_CATALOG = {
  "sourceDir": "GAC deliverables",
  "generatedAt": "2026-06-29",
  "categoryOrder": [
    "Outcome Reports",
    "Project Reporting & Management",
    "Training & Education",
    "Concept Notes & Agendas",
    "Attendance & Participation",
    "Communication Products",
    "Dialogues & Workshops",
    "Data & Technical",
    "Best Practices & Diagnostics",
    "Country Reports & Roadmaps",
    "Other Deliverables"
  ],
  "count": 135,
  "totalBytes": 557743278,
  "files": [
    {
      "name": "Attendance - 'Mas Alla del Fuego' Workshop (5 Dec 2025) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3101274,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Attendance - EWS Diagnostic Workshop (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3573987,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Attendance - IFM & EWS Workshop, Jimain - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 5278545,
      "category": "Attendance & Participation",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Attendance - National IFM Workshop (26 Aug 2025) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 14221970,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Attendance - WP3 Workshop (11 December) (ES) (copy).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 5011130,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Attendance - WP3 Workshop (11 December) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 5011130,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Attendance List 1 (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2684201,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Attendance List 2 (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 1516155,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Outcome 4.1 - FireData Workshop - Attendance List.pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3667987,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "Outcome 5.2 - Gender Workshop - Attendance List (Dec 2025).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 10132006,
      "category": "Attendance & Participation",
      "countries": []
    },
    {
      "name": "10 - Integrated Fire Management Paper.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 1825435,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "Best Practices - Fire Management Diagnostic (PT).xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 105859,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "Best Practices - IFM Papers Matrix.xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 31140,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "Best Practices - IFM Secondary Sources.xlsb",
      "ext": "xlsb",
      "type": "Excel",
      "sizeBytes": 37340,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "Diagnostic & Roadmap - Summary (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 1447455,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "DIMIF Caribe I - Systematization (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 1391026,
      "category": "Best Practices & Diagnostics",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "DIMIF Orinoquia - Executive Summary (EN, 16 Dec 2025) (copy).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 926904,
      "category": "Best Practices & Diagnostics",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "DIMIF Orinoquia - Executive Summary (EN, 16 Dec 2025).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 926904,
      "category": "Best Practices & Diagnostics",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "DIMIF Orinoquia - Systematization (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 625411,
      "category": "Best Practices & Diagnostics",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Evidence Compilation - Summary (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 10206979,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "IFM Diagnostic - FAO (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 871284,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "IFM Study - Final (23 March) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 4001126,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "IT Platform Diagnostic Questionnaire (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 518131,
      "category": "Best Practices & Diagnostics",
      "countries": []
    },
    {
      "name": "FireHub Communication Products (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 2662795,
      "category": "Communication Products",
      "countries": []
    },
    {
      "name": "IFM Networks (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 673746,
      "category": "Communication Products",
      "countries": []
    },
    {
      "name": "WTREX Infographic.pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 28223119,
      "category": "Communication Products",
      "countries": [
        "Regional"
      ]
    },
    {
      "name": "Agenda - 1st Forest Firefighter Tactical Group Mobilization (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 10467824,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Annex 4 - Concept Note - Colombia Workshop (March 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 137602,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Annex 5 - Methodology - Colombia Workshop (March 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 164196,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Annex 6 - Annotated Agenda - Colombia Workshop (March 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 242846,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Concept Note - 'Mas Alla del Fuego' Workshop (5 Dec 2025) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 634828,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - Agriculture Sector & Fire Workshop (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 410964,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - DIMIF Caribe I - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 730309,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Concept Note - DIMIF Orinoquia - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 633101,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Concept Note - DIMIF Pacifico - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 781723,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Concept Note - EWS Diagnostic Workshop (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 343454,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - Fire Risk Monitoring Workshop (11 Dec) (ES) (copy).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 228607,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - Fire Risk Monitoring Workshop (11 Dec) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 228607,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - IFM & EWS Workshop, Jimain - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 466883,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Concept Note - IFM Monitoring System Co-creation Workshop (ES) (copy).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 427525,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - IFM Monitoring System Co-creation Workshop (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 427525,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - Indigenous-led IFM Model.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 70850,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - Monteria Workshop - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 434671,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Concept Note - National Co-responsibility Strategy Workshop (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 248069,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - PSUI & NFO (Final).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 338055,
      "category": "Concept Notes & Agendas",
      "countries": []
    },
    {
      "name": "Concept Note - Valle del Cauca Workshop - Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 433720,
      "category": "Concept Notes & Agendas",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "01 - Comparative Report - IFM Initiatives in Bolivia & Peru (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 91233,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Bolivia"
      ]
    },
    {
      "name": "02 - IFM Initiatives & Indigenous Peoples - Bolivia (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 1355286,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Bolivia"
      ]
    },
    {
      "name": "03 - IFM Initiatives & Indigenous Peoples - Peru (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 2689645,
      "category": "Country Reports & Roadmaps",
      "countries": []
    },
    {
      "name": "04 - Country Report - Bolivia (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 560603,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Bolivia"
      ]
    },
    {
      "name": "05 - Country Report - Peru (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 6093456,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Peru"
      ]
    },
    {
      "name": "06 - Roadmap - Bolivia (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 381394,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Bolivia"
      ]
    },
    {
      "name": "07 - Roadmap - Bolivia (v2).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 160720,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Bolivia"
      ]
    },
    {
      "name": "08 - Roadmap - Peru (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 1168023,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Peru"
      ]
    },
    {
      "name": "09 - Roadmap - Peru (v2).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 1439246,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Peru"
      ]
    },
    {
      "name": "FAO Peru - Report (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 10505600,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Peru"
      ]
    },
    {
      "name": "IFM Roadmap - FAO (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 846502,
      "category": "Country Reports & Roadmaps",
      "countries": []
    },
    {
      "name": "Legal Report - IFM Application in Colombia (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 689130,
      "category": "Country Reports & Roadmaps",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Activity 1222.2 - Fire Module for MHEWS.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 1312952,
      "category": "Data & Technical",
      "countries": []
    },
    {
      "name": "Annex 2.1 - Regional Results (ES).xls",
      "ext": "xls",
      "type": "Excel",
      "sizeBytes": 337747,
      "category": "Data & Technical",
      "countries": [
        "Regional"
      ]
    },
    {
      "name": "Annex I - IFM Regulations Matrix - Latin America (ES).xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 86693,
      "category": "Data & Technical",
      "countries": [
        "Regional"
      ]
    },
    {
      "name": "Fire Danger Rating System (FDRS) - EWS LAC.xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 36649,
      "category": "Data & Technical",
      "countries": [
        "Regional"
      ]
    },
    {
      "name": "Fire Scar Mapping 2019 - Final Document (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2583577,
      "category": "Data & Technical",
      "countries": []
    },
    {
      "name": "IFM Cooperation Map (ES).xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 64142,
      "category": "Data & Technical",
      "countries": []
    },
    {
      "name": "IFM LAC - EWS Cooperation Mapping - Progress Report.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 5301193,
      "category": "Data & Technical",
      "countries": []
    },
    {
      "name": "Outcome 4.1 - FireData - Evaluation.xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 42290,
      "category": "Data & Technical",
      "countries": []
    },
    {
      "name": "SCCE Colombia - FAO 2025.pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3728640,
      "category": "Data & Technical",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "11 - National Dialogue - Bolivia (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 26688042,
      "category": "Dialogues & Workshops",
      "countries": [
        "Bolivia"
      ]
    },
    {
      "name": "12 - National Dialogue - Peru (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 3105649,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "13 - Binational Workshop - Peru & Bolivia (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 2036607,
      "category": "Dialogues & Workshops",
      "countries": [
        "Bolivia",
        "Peru",
        "Regional"
      ]
    },
    {
      "name": "14 - Pan-Amazon Workshop Report (EN).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 7358416,
      "category": "Dialogues & Workshops",
      "countries": [
        "Regional"
      ]
    },
    {
      "name": "Agriculture Sector & Fire - Workshop (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2118100,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "Annex 1 - Side Event - Indigenous Peoples & IFM (11 June 2025).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 174469,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "Annex 2 - Side Event - Global Hub Annual Meeting (16 Oct 2025).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 154267,
      "category": "Dialogues & Workshops",
      "countries": [
        "Regional"
      ]
    },
    {
      "name": "Annex 3 - Online Brainstorming Session Summary (18 Nov 2025).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 306623,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "Annex 7 - Intercultural Exchange Workshop Summary - Colombia (March 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 222372,
      "category": "Dialogues & Workshops",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Annex 9 - Intercultural Exchange Workshop Photos - Colombia (March 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 1163436,
      "category": "Dialogues & Workshops",
      "countries": [
        "Colombia"
      ]
    },
    {
      "name": "Forest Firefighter Tactical Group Mobilization - Report (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 1254507,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "IFM Information Workshops & Bill 557-2025 (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 270592,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "IFM Monitoring System Workshop - Executive Summary (ES).doc",
      "ext": "doc",
      "type": "Word",
      "sizeBytes": 32631,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "IFM Monitoring System Workshop - Plenary Findings (ES).doc",
      "ext": "doc",
      "type": "Word",
      "sizeBytes": 49406,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "National IFM Workshop - Colombia Institutions (26 Aug) (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 613963,
      "category": "Dialogues & Workshops",
      "countries": []
    },
    {
      "name": "Annex 8.1.pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 160337,
      "category": "Other Deliverables",
      "countries": []
    },
    {
      "name": "Outcome 1.1 - Report (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 679975,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 1.2 - Best Practices (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 845057,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 1.3 - Release (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 319545,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 2.1 - State Fire Policies (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3796748,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 3.1 - IFM Policies (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 682993,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 3.1 - IFM Policies Workshop (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2134686,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 4.1 - FireData (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 425917,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 4.2 - Algorithm Theoretical Basis Document (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 479352,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 4.2 - Dataset on Fuel Material (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 4196961,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 5.1 - Volunteer Brigades Workshop (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 4129769,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Outcome 5.2 - Gender Workshop (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 6803785,
      "category": "Outcome Reports",
      "countries": []
    },
    {
      "name": "Activity Report - FAO Colombia (19 Jun 2026) (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 952349,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Deliverables - Description & Titles.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 140828,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Ecuador Report - GCP GLO 1351 CAN (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 217235,
      "category": "Project Reporting & Management",
      "countries": [
        "Ecuador"
      ]
    },
    {
      "name": "Final Narrative Report - PSUI & NFO (copy).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 82573,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Final Narrative Report - PSUI & NFO.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 82576,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Final Report - FAO-IPAM (Brazil) (15 Mar 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 581623,
      "category": "Project Reporting & Management",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "FireHub Consultancy Report - LSW (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 1582660,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "FireHub Consultancy Report - RT (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 1595197,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "FUTERRA - Technical Final Report (20 Mar 2026).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 25333988,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "FUTERRA - Technical Final Report (20 Mar 2026).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2039369,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Links to Plenary Materials.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 6823,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Project CRT - GCP GLO 1351 CAN.xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 229822,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Project Indicators - GCP GLO 1351 CAN.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 69754,
      "category": "Project Reporting & Management",
      "countries": []
    },
    {
      "name": "Appendix 6 - Course Descriptions (ES).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 466871,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "Cartilha 01 - Integrated Fire Management (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3162200,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 02 - National IFM Policy PNMIF (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2569034,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 03 - IFM Plan PMIF (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 3370989,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 04 - Good Burning Practices (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 5282579,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 05 - Fire-Use Substitution Techniques (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 8502689,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 06 - Ecological Effects of Fire (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 5275378,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 07 - Glossary (PT) (copy).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2129328,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 07 - Glossary (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2129328,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 08 - PNMIF Regulations (PT) (copy).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2424402,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 08 - PNMIF Regulations (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 2424402,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha 09 - Coexistence with Fire (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 19401581,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha IFM - IPAM (Portuguese).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 9969404,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Cartilha IFM - IPAM (Spanish).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 9912076,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "Course Guide - IFM Plan PMIF (PT).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 54846911,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "GAC Report - IFM Assessment Tool.docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 47181,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "IFM Course - Chapter 1 (PT).pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 32950518,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "IFM Course - Chapter 2 (PT).pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 19870244,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "IFM Course - Chapter 3 (PT).pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 10017724,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "IFM Course - Chapter 4 (PT).pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 32167908,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "IFM Course - Chapter 5 (PT).pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 15671843,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "IFM Course - Chapter 6 (PT).pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 12142420,
      "category": "Training & Education",
      "countries": [
        "Brazil"
      ]
    },
    {
      "name": "IFM Self-Assessment Tool (26 Jun 2023).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 414600,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "IFM Workshops & Courses - Summary (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 6917530,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "Outcome 2.2 - Fire Behavior Course - Evaluation.xlsx",
      "ext": "xlsx",
      "type": "Excel",
      "sizeBytes": 41848,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "Outcome 2.2 - Fire Behavior Course - Report, Agenda & Attendance (EN).pdf",
      "ext": "pdf",
      "type": "PDF",
      "sizeBytes": 17940705,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "Presentation Template.pptx",
      "ext": "pptx",
      "type": "PowerPoint",
      "sizeBytes": 668987,
      "category": "Training & Education",
      "countries": []
    },
    {
      "name": "Travel Report - FAO Peru, Rioja S131 Course (ES).docx",
      "ext": "docx",
      "type": "Word",
      "sizeBytes": 7906477,
      "category": "Training & Education",
      "countries": [
        "Peru"
      ]
    }
  ]
};
