// ============================================================================
// FireHub — GAC deliverables catalog builder
// ----------------------------------------------------------------------------
// Scans the "GAC deliverables" source folder, classifies every document, and
// writes catalog-data.js (consumed by index.html). Re-run whenever documents
// are added/removed:  node scripts/build-catalog.mjs
// ----------------------------------------------------------------------------
// Classification: a file listed in scripts/classification.json uses that frozen
// category/country (files were renamed to clean titles, so we don't re-derive
// from the name). Any file NOT listed there falls back to the filename rules in
// classify.mjs — so new drops still get auto-classified; add them to the freeze
// later if needed.
// ============================================================================
import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join, extname, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { typeOf, categoryOf, countriesOf, CATEGORY_ORDER } from './classify.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const SRC_DIR = 'GAC deliverables'
const SRC_PATH = join(ROOT, SRC_DIR)
const OUT_PATH = join(ROOT, 'catalog-data.js')
const FROZEN_PATH = join(HERE, 'classification.json')

const frozen = existsSync(FROZEN_PATH) ? JSON.parse(readFileSync(FROZEN_PATH, 'utf8')) : {}

// ---- scan -------------------------------------------------------------------
const entries = readdirSync(SRC_PATH, { withFileTypes: true })
  .filter((d) => d.isFile())
  .map((d) => {
    const ext = extname(d.name)
    const { size } = statSync(join(SRC_PATH, d.name))
    const lock = frozen[d.name]
    return {
      name: d.name,
      ext: ext.replace(/^\./, '').toLowerCase(),
      type: typeOf(ext),
      sizeBytes: size,
      category: lock ? lock.category : categoryOf(d.name),
      countries: lock ? lock.countries : countriesOf(d.name),
    }
  })
  .sort((a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name))

const payload = {
  sourceDir: SRC_DIR,
  generatedAt: new Date().toISOString().slice(0, 10),
  categoryOrder: CATEGORY_ORDER,
  count: entries.length,
  totalBytes: entries.reduce((s, e) => s + e.sizeBytes, 0),
  files: entries,
}

writeFileSync(
  OUT_PATH,
  '// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.\n' +
    'window.FIREHUB_CATALOG = ' + JSON.stringify(payload, null, 2) + ';\n',
  'utf8',
)

// ---- console summary --------------------------------------------------------
const byCat = {}
for (const e of entries) byCat[e.category] = (byCat[e.category] || 0) + 1
const lockedN = entries.filter((e) => frozen[e.name]).length
console.log(`Indexed ${entries.length} files (${(payload.totalBytes / 1048576).toFixed(1)} MB, ${lockedN} frozen) -> catalog-data.js`)
for (const c of CATEGORY_ORDER) if (byCat[c]) console.log(`  ${String(byCat[c]).padStart(3)}  ${c}`)
