// ============================================================================
// FireHub — old → new filename map (single source of truth, pure export).
// Consumed by rename-files.mjs (apply/undo) and freeze-classification.mjs
// (to carry the original, known-good category/country onto the new names).
// Keys are the ORIGINAL on-disk filenames; values are the clean new names.
// ============================================================================
export const MAP = {
  // ---- Attendance & Participation -----------------------------------------
  '4.1.FireData_attendance_list.pdf': 'Outcome 4.1 - FireData Workshop - Attendance List.pdf',
  '5.2.attendance_list_genre_workshop_dez25.pdf': 'Outcome 5.2 - Gender Workshop - Attendance List (Dec 2025).pdf',
  'Asistencia Taller Diagnóstico SAT.pdf': 'Attendance - EWS Diagnostic Workshop (ES).pdf',
  'Asistencia Taller Nacional MIF 26 de agosto 2025.PDF': 'Attendance - National IFM Workshop (26 Aug 2025) (ES).pdf',
  'Lista De Asistencia Wp3 - Taller 11 De Diciembre (1).PDF': 'Attendance - WP3 Workshop (11 December) (ES).pdf',
  'Lista De Asistencia Wp3 - Taller 11 De Diciembre.PDF': 'Attendance - WP3 Workshop (11 December) (ES) (copy).pdf',
  'Lista Taller Más Allá del Fuego 5 diciembre 2025.PDF': "Attendance - 'Mas Alla del Fuego' Workshop (5 Dec 2025) (ES).pdf",
  'Listado de Asistencia (1).pdf': 'Attendance List 1 (ES).pdf',
  'Listado de Asistencia.PDF': 'Attendance List 2 (ES).pdf',
  'Listas de asistencia Taller Manejo Integral del Fuego- SAT Jimain..PDF': 'Attendance - IFM & EWS Workshop, Jimain - Colombia (ES).pdf',

  // ---- Best Practices & Diagnostics ---------------------------------------
  '10 - IFM Paper.docx': '10 - Integrated Fire Management Paper.docx',
  'BestPractices_MIF_diagnostico gestao do fogo.xlsx': 'Best Practices - Fire Management Diagnostic (PT).xlsx',
  'BestPractices_MIF_papers.xlsx': 'Best Practices - IFM Papers Matrix.xlsx',
  'BestPractices_MIF_secundarios.xlsb': 'Best Practices - IFM Secondary Sources.xlsb',
  'Cuestionario Diagnostico Plataforma Informatica.PDF': 'IT Platform Diagnostic Questionnaire (ES).pdf',
  'Diagnóstico MIF FAO.pdf': 'IFM Diagnostic - FAO (ES).pdf',
  'ESTUDIO MIF FINAL 23marzo.pdf': 'IFM Study - Final (23 March) (ES).pdf',
  'Executive Summary DIMIF Orinoquía_english_16.12.2025 (1).pdf': 'DIMIF Orinoquia - Executive Summary (EN, 16 Dec 2025).pdf',
  'Executive Summary DIMIF Orinoquía_english_16.12.2025.pdf': 'DIMIF Orinoquia - Executive Summary (EN, 16 Dec 2025) (copy).pdf',
  'Resumen diagnóstico y hoja de ruta.docx': 'Diagnostic & Roadmap - Summary (ES).docx',
  'Resumen Recopilación de evidencias.docx': 'Evidence Compilation - Summary (ES).docx',
  'Sistematización _DIMIF_Caribe I.pdf': 'DIMIF Caribe I - Systematization (ES).pdf',
  'Sistematización_DIMIF_Orinoquia.pdf': 'DIMIF Orinoquia - Systematization (ES).pdf',

  // ---- Communication Products ---------------------------------------------
  'Infografía WTREX.pdf': 'WTREX Infographic.pdf',
  'Mif redes - pdf.pdf': 'IFM Networks (ES).pdf',
  'Productos Comunicacion FireHub.docx': 'FireHub Communication Products (ES).docx',

  // ---- Concept Notes & Agendas --------------------------------------------
  'Agenda 1era MOVILIZACIÓN GTBF.PDF': 'Agenda - 1st Forest Firefighter Tactical Group Mobilization (ES).pdf',
  'Annex 4. Concept Note- Colombia Workshop March 2026.pdf': 'Annex 4 - Concept Note - Colombia Workshop (March 2026).pdf',
  'Annex 5. Methodology- Colombia Wokshop March 2026.pdf': 'Annex 5 - Methodology - Colombia Workshop (March 2026).pdf',
  'Annex 6. Annotated Agenda  Colombia Workshop-March 2026.pdf': 'Annex 6 - Annotated Agenda - Colombia Workshop (March 2026).pdf',
  'Concept Note Indigenous-led IFM model v0.docx': 'Concept Note - Indigenous-led IFM Model.docx',
  'Concept Note- PSUI NFO-Final.pdf': 'Concept Note - PSUI & NFO (Final).pdf',
  'NC - Montería.pdf': 'Concept Note - Monteria Workshop - Colombia (ES).pdf',
  'NC - Valle del Cauca.PDF': 'Concept Note - Valle del Cauca Workshop - Colombia (ES).pdf',
  'NC DIMIF Caribe I V3. 2601226.pdf': 'Concept Note - DIMIF Caribe I - Colombia (ES).pdf',
  'NC DIMIF Orinoquía V.21112025.pdf': 'Concept Note - DIMIF Orinoquia - Colombia (ES).pdf',
  'NC DIMIF Pacifico V.30032026.pdf': 'Concept Note - DIMIF Pacifico - Colombia (ES).pdf',
  'NC TALLER DE MANEJO INTEGRAL DEL FUEGO Y SAT Jimain.PDF': 'Concept Note - IFM & EWS Workshop, Jimain - Colombia (ES).pdf',
  'NC Taller Diagnóstico SAT.pdf': 'Concept Note - EWS Diagnostic Workshop (ES).pdf',
  'NC Taller Más Allá del Fuego 5 Diciembre 2025.PDF': "Concept Note - 'Mas Alla del Fuego' Workshop (5 Dec 2025) (ES).pdf",
  'NC Taller Retos y Desafío del Sector AGRO frente al fuego.PDF': 'Concept Note - Agriculture Sector & Fire Workshop (ES).pdf',
  'Nota concepto Taller Nacional de Socializacion Estrategia Nacional de Corresponsabilidad.PDF': 'Concept Note - National Co-responsibility Strategy Workshop (ES).pdf',
  'Nota de concepto_TALLER_Monitoreo Gestión Riesgo Incendios_lm_dic11_OK (1).PDF': 'Concept Note - Fire Risk Monitoring Workshop (11 Dec) (ES).pdf',
  'Nota de concepto_TALLER_Monitoreo Gestión Riesgo Incendios_lm_dic11_OK.PDF': 'Concept Note - Fire Risk Monitoring Workshop (11 Dec) (ES) (copy).pdf',
  'NotaConcepto Taller co-creación del SMF IF VF (1).PDF': 'Concept Note - IFM Monitoring System Co-creation Workshop (ES).pdf',
  'NotaConcepto Taller co-creación del SMF IF VF.PDF': 'Concept Note - IFM Monitoring System Co-creation Workshop (ES) (copy).pdf',

  // ---- Country Reports & Roadmaps -----------------------------------------
  '1 - Reporte Comparativo sobre Iniciativas de Manejo Integral del Fuego en Bolivia y Perú.docx': '01 - Comparative Report - IFM Initiatives in Bolivia & Peru (ES).docx',
  '2 - Iniciativas de manejo integral del fuego y participación de pueblos indígenas en Bolivia.docx': '02 - IFM Initiatives & Indigenous Peoples - Bolivia (ES).docx',
  '3 - Iniciativas de manejo integral del fuego y participación de pueblos indígenas en Perú.docx': '03 - IFM Initiatives & Indigenous Peoples - Peru (ES).docx',
  '4 - Bolivia.docx': '04 - Country Report - Bolivia (ES).docx',
  '5 - Peru.docx': '05 - Country Report - Peru (ES).docx',
  '6 - Roadmap - Bolivia.docx': '06 - Roadmap - Bolivia (ES).docx',
  '7 - Roadmap - Bolívia.docx': '07 - Roadmap - Bolivia (v2).docx',
  '8 - Roadmap - Peru.docx': '08 - Roadmap - Peru (ES).docx',
  '9 - Roadmap - Peru.docx': '09 - Roadmap - Peru (v2).docx',
  'GAC_FAOPERU_Informe.docx': 'FAO Peru - Report (ES).docx',
  'Hoja de ruta MIF FAO.pdf': 'IFM Roadmap - FAO (ES).pdf',
  'Informe jurídico sobre la aplicación del Manejo Integrado del Fuego en Colombia.PDF': 'Legal Report - IFM Application in Colombia (ES).pdf',

  // ---- Data & Technical ----------------------------------------------------
  '4.1.FireData evaluation.xlsx': 'Outcome 4.1 - FireData - Evaluation.xlsx',
  'Activity 1222.2 Fire Module for MHEWS v0.docx': 'Activity 1222.2 - Fire Module for MHEWS.docx',
  'Anexo 2.1 Resultados regional VF.XLS': 'Annex 2.1 - Regional Results (ES).xls',
  'Anexo I - Matriz de normativa MIF America Latina.xlsx': 'Annex I - IFM Regulations Matrix - Latin America (ES).xlsx',
  'Documento final EET Mapa Cicatrices de Incendio 2019 vf.PDF': 'Fire Scar Mapping 2019 - Final Document (ES).pdf',
  'FDRS_EWS_LAC.xlsx': 'Fire Danger Rating System (FDRS) - EWS LAC.xlsx',
  'IFM-LAC_Coop_EWS_Mapping_Progress Report_for_clerance.docx': 'IFM LAC - EWS Cooperation Mapping - Progress Report.docx',
  'mapa_cooperación_MIF.xlsx': 'IFM Cooperation Map (ES).xlsx',
  'SCCE_Colombia_FAO2025 (2).PDF': 'SCCE Colombia - FAO 2025.pdf',

  // ---- Dialogues & Workshops ----------------------------------------------
  '11 - Diálogo Nacional Bolivia.docx': '11 - National Dialogue - Bolivia (ES).docx',
  '12 - Diálogo Nacional Perú.docx': '12 - National Dialogue - Peru (ES).docx',
  '13 - Taller Binacional Peru-Bolivia.docx': '13 - Binational Workshop - Peru & Bolivia (ES).docx',
  '14 - Pan-Amazon Workshop Report.docx': '14 - Pan-Amazon Workshop Report (EN).docx',
  'Annex 1. first side event on Indigenous Peoples and IFM 11June25.pdf': 'Annex 1 - Side Event - Indigenous Peoples & IFM (11 June 2025).pdf',
  'Annex 2. second side event Global Hub annual meeting 16Oct2025.pdf': 'Annex 2 - Side Event - Global Hub Annual Meeting (16 Oct 2025).pdf',
  'Annex 3. Summary of online Brainstorming Session-18Nov2025.pdf': 'Annex 3 - Online Brainstorming Session Summary (18 Nov 2025).pdf',
  'Annex 7. Summary report Intercultural Exchange Workshp Colombia- March 2026.pdf': 'Annex 7 - Intercultural Exchange Workshop Summary - Colombia (March 2026).pdf',
  'Annex 9. Photos Intercultural Knowledge Exchange Workshop Colombia March 2026.pdf': 'Annex 9 - Intercultural Exchange Workshop Photos - Colombia (March 2026).pdf',
  'Hallazgos_Plenarias_Taller_Nacional_Co-creación_SMIF.DOC': 'IFM Monitoring System Workshop - Plenary Findings (ES).doc',
  'Informe Movilización Grupos Tácticos  de Bomberos Forestales.PDF': 'Forest Firefighter Tactical Group Mobilization - Report (ES).pdf',
  'Resumen_Ejecutivo_Taller_Nacional_Co-creación_SMIF.DOC': 'IFM Monitoring System Workshop - Executive Summary (ES).doc',
  'Taller Nacional de MIF_FAO_MADR-MADS-UNGRD-DNBC_26 Agost.PDF': 'National IFM Workshop - Colombia Institutions (26 Aug) (ES).pdf',
  'Taller Retos y desafíos del sector Agro frente al fuego.PDF': 'Agriculture Sector & Fire - Workshop (ES).pdf',
  'Talleres Informativos sobre Manejo Integral del Fuego y la iniciativa legislativa Proyecto de Ley 557 de 2025.PDF': 'IFM Information Workshops & Bill 557-2025 (ES).pdf',

  // ---- Other Deliverables --------------------------------------------------
  'ANNEX8_1.PDF': 'Annex 8.1.pdf',

  // ---- Outcome Reports -----------------------------------------------------
  '1.2. Report Outcome1_2 v27_02_2026_Best practices_EN.pdf': 'Outcome 1.2 - Best Practices (EN).pdf',
  '1.3. Report Outcome1_3 v02_03_2026_Release.pdf': 'Outcome 1.3 - Release (EN).pdf',
  '2.1.Report Outcome2_1 v19_02_2026_state fire policies_EN.pdf': 'Outcome 2.1 - State Fire Policies (EN).pdf',
  '3.1.Report Outcome3_1 v23_02_2026_MIF policies_EN.pdf': 'Outcome 3.1 - IFM Policies (EN).pdf',
  '3.1.Report Outcome3_1 v23_02_2026_MIF workshop_EN.pdf': 'Outcome 3.1 - IFM Policies Workshop (EN).pdf',
  '4.1.Report Outcome4_1 v20_02_2026_FireData.pdf': 'Outcome 4.1 - FireData (EN).pdf',
  '4.2.Report Outcome4_2 v20_02_2026_Algorithm Theoretical Basis Document.pdf': 'Outcome 4.2 - Algorithm Theoretical Basis Document (EN).pdf',
  '4.2.Report Outcome4_2 v20_02_2026_Dataset on fuel material.pdf': 'Outcome 4.2 - Dataset on Fuel Material (EN).pdf',
  '5.1.Report Outcome5_2 v20_02_2026_volunteer brigades workshop_EN.pdf': 'Outcome 5.1 - Volunteer Brigades Workshop (EN).pdf',
  '5.2.Report Outcome5_2 v20_02_2026_gender workshop_EN.pdf': 'Outcome 5.2 - Gender Workshop (EN).pdf',
  'Report Outcome1_1 v07012026.pdf': 'Outcome 1.1 - Report (EN).pdf',

  // ---- Project Reporting & Management -------------------------------------
  '4 - indicators - GCP GLO 1351 CAN.docx': 'Project Indicators - GCP GLO 1351 CAN.docx',
  'Deliverables Description and titles.docx': 'Deliverables - Description & Titles.docx',
  'FAO-IPAM-GCP_GLO_1351_CAN v15032026 Final Report.pdf': 'Final Report - FAO-IPAM (Brazil) (15 Mar 2026).pdf',
  'Final Narrative Report-PSUI and NFO (1).docx': 'Final Narrative Report - PSUI & NFO.docx',
  'Final Narrative Report-PSUI and NFO.docx': 'Final Narrative Report - PSUI & NFO (copy).docx',
  'FUTERRA - Final Report Technical - Final 2026_3_20.docx': 'FUTERRA - Technical Final Report (20 Mar 2026).docx',
  'FUTERRA - Final Report Technical - Final 2026_3_20.pdf': 'FUTERRA - Technical Final Report (20 Mar 2026).pdf',
  'GCP GLO1351 CAN_CRT.xlsx': 'Project CRT - GCP GLO 1351 CAN.xlsx',
  'Informe Consultoria FireHub - LSW Vs.pdf': 'FireHub Consultancy Report - LSW (ES).pdf',
  'Informe Consultoria FireHub - RT Vs.pdf': 'FireHub Consultancy Report - RT (ES).pdf',
  'Informe de Actividades GCP 1351_FAOCO_19062026.docx': 'Activity Report - FAO Colombia (19 Jun 2026) (ES).docx',
  'InformeEcuador_GAC_GCP_GLO_1351_CAN_vpj - Copiar.docx': 'Ecuador Report - GCP GLO 1351 CAN (ES).docx',
  'Links to Plenary materials.docx': 'Links to Plenary Materials.docx',

  // ---- Training & Education ------------------------------------------------
  '2.2.Fire behavior course ourse evaluation.xlsx': 'Outcome 2.2 - Fire Behavior Course - Evaluation.xlsx',
  '2.2.Report v04_03_2026_Fire behavior course_EN_agenda_AttendanceList.pdf': 'Outcome 2.2 - Fire Behavior Course - Report, Agenda & Attendance (EN).pdf',
  '260623 IFM self assessment tool.docx': 'IFM Self-Assessment Tool (26 Jun 2023).docx',
  'Apéndice 6. Fichas_Descriptivas_Cursos.PDF': 'Appendix 6 - Course Descriptions (ES).pdf',
  'Capítulo 1.pptx': 'IFM Course - Chapter 1 (PT).pptx',
  'Capítulo 2.pptx': 'IFM Course - Chapter 2 (PT).pptx',
  'Capítulo 3.pptx': 'IFM Course - Chapter 3 (PT).pptx',
  'Capítulo 4.pptx': 'IFM Course - Chapter 4 (PT).pptx',
  'Capítulo 5.pptx': 'IFM Course - Chapter 5 (PT).pptx',
  'Capítulo 6.pptx': 'IFM Course - Chapter 6 (PT).pptx',
  'Cartilha MIF - IPAM - A5 ESPANHOL V4 digital.pdf': 'Cartilha IFM - IPAM (Spanish).pdf',
  'Cartilha MIF - IPAM - A5 PORTUGUES V10 DIGITAL.pdf': 'Cartilha IFM - IPAM (Portuguese).pdf',
  'Cartilha-01-MIF_V3_final.pdf': 'Cartilha 01 - Integrated Fire Management (PT).pdf',
  'Cartilha-02-PNMIF_V3_final.pdf': 'Cartilha 02 - National IFM Policy PNMIF (PT).pdf',
  'Cartilha-03-PMIF_V3_final.pdf': 'Cartilha 03 - IFM Plan PMIF (PT).pdf',
  'Cartilha-04-BoasPraticasQueimas_V3_final.pdf': 'Cartilha 04 - Good Burning Practices (PT).pdf',
  'Cartilha-05-TecnicasSubstituicaoUsoFogo_V5_final.pdf': 'Cartilha 05 - Fire-Use Substitution Techniques (PT).pdf',
  'Cartilha-06-EfeitosEcologicosFogo_V3_final.pdf': 'Cartilha 06 - Ecological Effects of Fire (PT).pdf',
  'Cartilha-07-Glossario_V4_final (1).pdf': 'Cartilha 07 - Glossary (PT).pdf',
  'Cartilha-07-Glossario_V4_final.pdf': 'Cartilha 07 - Glossary (PT) (copy).pdf',
  'Cartilha-08-PNMIF-Regulamentacoes_V3_final (1).pdf': 'Cartilha 08 - PNMIF Regulations (PT).pdf',
  'Cartilha-08-PNMIF-Regulamentacoes_V3_final.pdf': 'Cartilha 08 - PNMIF Regulations (PT) (copy).pdf',
  'Cartilha-09-Convivencia-MIF_V3_final.pdf': 'Cartilha 09 - Coexistence with Fire (PT).pdf',
  'GAC report IFM assessment tool (1).docx': 'GAC Report - IFM Assessment Tool.docx',
  'Guia Curso PMIF_V3_final.pdf': 'Course Guide - IFM Plan PMIF (PT).pdf',
  'Informe de Viaje FAO PE RIOJA Curso S131.docx': 'Travel Report - FAO Peru, Rioja S131 Course (ES).docx',
  'Modelo (1).pptx': 'Presentation Template.pptx',
  'Resumen Talleres y Cursos MIF.docx': 'IFM Workshops & Courses - Summary (ES).docx',
}
